### ISSUE TITLE
Updated GB and GBC cores now support all display mods + custom display modes

### ISSUE THREAD

**Issue by 825i** [ninbura/pokemon-on-the-analogue-pocket#1]
Title.

Unfortunately though flashcarts are still the best way to play :(

Neither .pocket nor cores have the ability to do RTC. If you really want a proper RTC you need a flashcart... or original or custom cartridge with a built-in battery to load your .rom file on.

**Comment by ninbura** [comment]
There's actually a new [GB/GBC core](https://github.com/budude2/openfgpa-GBC) that does RTC.

However, it's pretty buggy at the moment. There's currently no sleep/save state implementation, and once it's introduced it's possible that utilizing state management could de-sync RTC. I was giving it a bit more time before integrating it into my guide, hoping he'd iron out a few bugs and implement sleep/save states.

I'll update the guide soon.

**Comment by ninbura** [comment]
I've updated the guide to account for all topics mentioned in this issue.
