### ISSUE TITLE
You don't have to have any physical carts to move Pokemon from Gen 3 to Bank. Or checkpoint for that matter.

### ISSUE THREAD

**Issue by GoodoDarco** [ninbura/pokemon-on-the-analogue-pocket#3]
It's a little bit more involved, but you can [use MelonDS to transfer from a Gen 4 ROM to a Gen 5 ROM](https://melonds.kuribo64.net/board/thread.php?pid=3109), then use [DreamRadarCartRedirect](https://github.com/zaksabeast/DreamRadarCartRedirect) to spoof Poké Transporter to use a B/W/B2/W2 ROM you've loaded into [TwilightMenu++](https://github.com/DS-Homebrew/TWiLightMenu), then import that to Bank. The only actual physical requirement of this whole process is a [Hacked 3DS](https://3ds.hacks.guide). And that's because Citra is a wee bit wacky with Nintendo's servers. 

This is less of a circumvention of checkpoint and moreso a circumvention of all physical carts, because legit physicals are expensive (there's flash carts, but it's a confusing market).

Source: uhh I just did it

**Comment by ninbura** [comment]
Thank you for this info 🙏 

I've linked to this issue in the [interfacing with Pokémon Home](https://github.com/ninbura/pokemon-on-the-analogue-pocket?tab=readme-ov-file#interfacing-with-Pok%C3%A9mon-Home) section of the readme.
