### ISSUE TITLE
Update for new Omega DE FW

### ISSUE THREAD

**Issue by wmtorode** [ninbura/pokemon-on-the-analogue-pocket#5]
EZ-Flash has just released a new firmware update for the Omega DE (Kernel 1.05, FW 7) which fixes Mode B on the pocket for Rev B of the Omega DE (no idea if it fixes the issue for users with Rev A hardware). this should allow it to work with the pocket's native sleep mode again.

**Comment by ninbura** [comment]
Just flashed the Kernel and upgraded the Firmware and it does appear to work. Incredible news, interesting that it contradicts EZ-Flash stating that the fix needed to be on Analogue's end not too long ago. Maybe the just got around to looking at the Pocket I sent them.

Did EZ-Flash state anywhere that the update was supposed to fix Mode B on Analogue Pocket? Or did you just test it and noticed it worked?

**Comment by logantalley** [comment]
I can confirm it works! But want to know if RTC will de-sync on sleep. Too invested in my save file to test it myself lol

**Comment by wmtorode** [comment]
came across a thread on reddit and confirmed it was working, so figured I'd give you a heads up. Thread: [Mode B Fixed](https://www.reddit.com/r/AnaloguePocket/comments/1f8pbay/omega_de_mode_b_finally_works_on_ap_w_sleep_rev_b/)

I don't think EZ-flash fixed it on purpose but in their change notes for FW 7:

Changelog

Firmware7 for Rev.B
Added support for S98 chips with 020 suffixes.

S98 is the nor flash chip, so they are swapping to a different version (because the current one is obsolete and out of production), so I'm theorizing that it likely had different timings or something and that was just enough to get the pocket working with it

**Comment by logantalley** [comment]
Just an update, sleep works without de-syncing RTC. Not sure how fragile that is, but it seems to be working!

**Comment by ninbura** [comment]
I just tested myself, and everything seems to be working without de-sync. I updated the readme to reflect this development. 

I'm going to reach out to EZ-Flash and see if they were aware that this fixes Mode B.

Keep me posted if you guys run into any issues, I'll do the same. Thanks the help 🙏

**Comment by wmtorode** [comment]
looks like EZ-Flash didn't intentionally fix it, just a happy coincidence: https://gbatemp.net/threads/ez-flash-omega-and-omega-definitive-edition-sep-2024-update.660438/

> Maybe you have heard that the Rev.B upgraded to FW7 has liberated a certain function on a certain product. We can only say that this is just a coincidence. This will not be officially recognized by us or included in the official update list.

but either way I'm happy that its working

**Comment by ninbura** [comment]
> Maybe you have heard that the Rev.B upgraded to FW7 has liberated a certain function on a certain product. We can only say that this is just a coincidence. This will not be officially recognized by us or included in the official update list.

Their wording is extremely weird there. Almost sounds like it was intentional but they have some interest in not saying so. Saying "liberated a certain function on a certain product" is directly indirect. From my understanding Analogue has always been pretty coy with flash cart manufacturers. 

But yeah I agree, the important thing is that it's working.
